# Utiliser une image Node.js officielle
FROM node:16

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers package.json et package-lock.json
COPY package*.json /app/

# Installer les dépendances
RUN npm install

# Copier le reste du code source
COPY . /app/

# Construire l'application React pour la production
RUN npm run build

# Exposer le port 3000 pour l'application React
EXPOSE 3000

# Commande pour démarrer l'application React
CMD ["npm", "start"]