name: Deploy to Production

on:
  push:
    branches:
      - main  # Trigger the workflow only on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Docker Buildx (for cross-platform builds, if needed)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Login to DockerHub using secrets
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t lionyti/ml_in_prod:latest .
      
      # 5. Push the Docker image to DockerHub
      - name: Push Docker image to DockerHub
        run: |
          docker push lionyti/ml_in_prod:latest

      # 6. Deploy the Docker image to production
      - name: Deploy to production
        run: |
          echo "Deploying to production..."
          docker-compose -f docker-compose.prod.yml up -d
