name: Deploy to Production

# Trigger workflow when a pull request is created or pushed to the main branch.
on:
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Docker Buildx (for cross-platform builds, if needed)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 3. Login to DockerHub using secrets
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 4. Build both Docker images using docker-compose
      - name: Build Docker images using docker-compose
        run: |
          docker-compose -f docker-compose.prod.yml build

      # 5. Push both Docker images to DockerHub using docker-compose
      - name: Push Docker images to DockerHub
        run: |
          docker-compose -f docker-compose.prod.yml push

      # 6. Deploy the Docker images to production using docker-compose
      - name: Deploy to production
        run: |
          docker-compose -f docker-compose.prod.yml up -d
