version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: lionyti/frontend:latest
    ports:
      - "3000:3000" 
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: lionyti/backend:latest
    ports:
      - "5000:5000"
    restart: always
