name: On Push to Staging

on:
  push:
    branches:
      - staging

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout du code source
    - name: Checkout code
      uses: actions/checkout@v3

    # Configuration Node.js pour le frontend
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Installer les dépendances et construire le frontend
    - name: Install and build frontend
      working-directory: ./frontend
      run: |
        npm install
        npm run build

    # Installer Python pour le backend
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    # Installer les dépendances et exécuter les tests backend
    - name: Install and test backend
      working-directory: ./backend
      run: |
        pip install -r requirements.txt
        pytest

  push-to-main:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
    # Checkout du code source
    - name: Checkout code
      uses: actions/checkout@v3

    # Pousser vers la branche main
    - name: Push to main branch
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git checkout -b main
        git push origin main --force
