name: pr-to-dev

on:
  pull_request:
    branches:
      - dev

jobs:
  docker-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
        with:
          version: latest

      - name: Set up Docker Compose
        run: |
          sudo apt-get install -y docker-compose

      - name: Build and run containers with docker-compose
        run: |
          docker-compose up -d  # Démarre les services en arrière-plan

      - name: Wait for services to be ready
        run: |
          # Attendre quelques secondes que les services soient prêts
          sleep 10

      - name: Run frontend tests
        run: |
          # Exécute les tests frontend dans le conteneur
          docker-compose exec frontend npm test
          # Vérifiez que les tests frontend réussissent
          if [ $? -ne 0 ]; then
            echo "Frontend tests failed"
            exit 1
          fi

      - name: Run backend tests
        run: |
          # Exécute les tests backend dans le conteneur (si applicable)
          docker-compose exec backend pytest
          # Vérifiez que les tests backend réussissent
          if [ $? -ne 0 ]; then
            echo "Backend tests failed"
            exit 1
          fi

      - name: Shutdown Docker Compose
        run: |
          docker-compose down

      - name: Mark PR as successfully completed
        run: |
          echo "PR-to-dev completed successfully!"
