name: Pull Request to Dev

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      # Run integration tests
      - name: Run integration tests
        run: npm run test:integration

      # This is the final step where you manually merge after the workflow succeeds
      - name: Waiting for manual merge
        run: echo "Everything looks good. Please manually merge into dev."