name: Push to Staging

on:
  push:
    branches:
      - dev

jobs:
  push-to-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git config
        run: |
          git config user.name "Fabien-TCL"
          git config user.email "fabien.tuncel@efrei.net"
          
      - name: Checkout or create staging branch
        run: |
          git checkout -b staging || git checkout staging

      - name: Push to staging
        run: |
          git remote set-url origin https://github.com/${{ github.repository }}.git
          git push origin staging
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}