name: Push to Main

on:
  workflow_run:
    workflows: ["pr-to-dev"]  # Le workflow sera déclenché uniquement après l'exécution de "pr-to-dev"
    types:
      - completed  # Nous attendons que "pr-to-dev" se termine avant d'exécuter celui-ci

jobs:
  push-to-main:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configure Git
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"

      # 3. Fetch the latest changes from origin and ensure we are on the main branch
      - name: Fetch and check out main
        run: |
          git fetch origin
          git checkout main
          git pull origin main

      # 4. Merge origin/dev into main
      - name: Merge dev into main
        run: |
          git merge origin/dev --no-ff --commit -m "Merge branch 'dev' into 'main' via GitHub Actions"
          # Vérifiez si le merge est effectué sans conflit

      # 5. Push changes to main
      - name: Push to main
        run: |
          git push origin main
