name: Push to Main

on:
  pull_request:
    branches:
      - dev

jobs:
  push-to-main:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configure Git
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"

      # 3. Merge dev into main
      - name: Merge dev into main
        run: |
          git fetch origin
          git checkout main
          git merge dev --no-ff --commit -m "Merge branch 'dev' into 'main' via GitHub Actions"

      # 4. Push changes to main
      - name: Push to main
        run: |
          git push origin main
