name: Push to Staging

on:
  push:
    branches:
      - dev

jobs:
  push-to-staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Configure Git user
      - name: Set up Git config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@github.com"
          
      # Checkout staging branch, or create it if it doesn't exist
      - name: Checkout or create staging branch
        run: |
          git checkout -b staging || git checkout staging

      # Push changes to staging branch using the personal access token (PAT)
      - name: Push to staging
        run: |
          git remote set-url origin https://github.com/${{ github.repository }}.git
          git push origin staging
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}